[build-system]
requires = ["setuptools", "wheel"]
# build-backend = "setuptools.build_meta"

[tool.black]
line-length = 110
target-version = ['py39']

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
files = "src/"