name: Run python tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run the pytest suite
        working-directory: src
        run: |
          pytest
