name: Run python tests for the extraction script
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install jieba
          pip install pytest
          pip install flake8
          pip install mypy
      - name: flake8 linter
        working-directory: dict
        run: |
          flake8 extract.py
          flake8 extract_test.py
      - name: mypy check
        working-directory: dict
        run: |
          mypy extract.py
      - name: run the pytest suite
        working-directory: dict
        run: |
          pytest 
